name: SortyQuizz app CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: merlinofcha0s/flutter-ci:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter pub get
    - name: Building APK
      run: flutter build apk --release
    - name: Building app bundle
      run: flutter build appbundle --target-platform android-arm,android-arm64,android-x64
    - name: Archiving APK
      uses: actions/upload-artifact@v1
      with:
          name: SortyQuizz-apk
          path: build/app/outputs/bundle/release
    - name: Archiving APP Bundle
      uses: actions/upload-artifact@v1
      with:
          name: SortyQuizz-bundle
          path: build/app/outputs/bundle/release
